name: 双向极简同步
on:
  workflow_dispatch
  schedule:
    - cron: 0 0 * * *
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: 运行双向同步
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_TOKEN_PAGE: ${{ secrets.NOTION_PAGE_ID }}
        run: echo 通道正常
